# Naive Bayes Algorithm Explained

Naive Bayes is a **probabilistic machine learning algorithm** used for **classification problems**. It is based on **Bayes' Theorem** and is called **"naive"** because it assumes that all features (input variables) are **independent** of each other (even though this may not be true in practice). Let's break it down step by step:

---

## 1. **What is Bayes' Theorem?**
Bayes' Theorem is a way to calculate probabilities. The formula is:

$$
P(A|B) = \frac{P(B|A) \cdot P(A)}{P(B)}
$$


- **\(P(A|B)\)**: Probability of event A given that B has already occurred (Posterior Probability).
- **\(P(B|A)\)**: Probability of event B given that A has already occurred (Likelihood).
- **\(P(A)\)**: Probability of event A (Prior Probability).
- **\(P(B)\)**: Probability of event B (Marginal Probability).

---

## 2. **How Does Naive Bayes Work?**
Naive Bayes is used for classification. For example, if we want to predict whether an email is **spam** or **not spam**, Naive Bayes works as follows:

### Training Phase:
- Calculate probabilities from the dataset, such as:
- **$P(\text{Spam})$**: Probability that an email is spam.  
- **$P(\text{Not Spam})$**: Probability that an email is not spam.  
- **$P(\text{Word}_i|\text{Spam})$**: Probability that a specific word appears in an email if it is spam.  
- **$P(\text{Word}_i|\text{Not Spam})$**: Probability that a specific word appears in an email if it is not spam.  


### Testing Phase:
- For a new email, the algorithm calculates:
- **$P(\text{Spam}|\text{Email})$**: Probability that the email is spam.  
- **$P(\text{Not Spam}|\text{Email})$**: Probability that the email is not spam.  

- The final prediction is based on the higher probability.

---

## 3. **Why is Naive Bayes "Naive"?**
- The algorithm assumes that all features (words in an email) are **independent** of each other. This means the probability of one word does not depend on the presence of another word.
- Example: If an email contains the words "free" and "offer," Naive Bayes treats them as independent, even though in reality, these words together might increase the likelihood of the email being spam.

---

## 4. **Types of Naive Bayes**
1. **Gaussian Naive Bayes**: Used for continuous data.
2. **Multinomial Naive Bayes**: Used for discrete data (e.g., word counts).
3. **Bernoulli Naive Bayes**: Used for binary data (0 or 1).

---

## 5. **Example: Spam Detection**
### Training Data:
- Total emails: 100
- Spam emails: 30
- Not spam emails: 70
- Probability of the word "free" in spam emails:
$$P(\text{free}|\text{Spam}) = 0.6$$

- Probability of the word "free" in not spam emails:
$$P(\text{free}|\text{Not Spam}) = 0.1$$


### New Email: "Get free money now"
- Calculate:
$$P(\text{Spam}|\text{free}) = \frac{P(\text{free}|\text{Spam}) \cdot P(\text{Spam})}{P(\text{free})}$$

$$P(\text{Not Spam}|\text{free}) = \frac{P(\text{free}|\text{Not Spam}) \cdot P(\text{Not Spam})}{P(\text{free})}$$

If **P(Spam|free)** is higher, classify the email as spam.

---

## 6. **Advantages of Naive Bayes**
- Simple and fast.
- Works well with small datasets.
- Effective for high-dimensional data (e.g., text data).

---

## 7. **Disadvantages of Naive Bayes**
- Assumes features are independent, which may not be true in real-world scenarios.
- If a feature is not present in the training data, its probability becomes 0, which can reduce accuracy.

---

## 8. **Real-Life Applications**
- Spam detection
- Sentiment analysis
- Document classification
- Medical diagnosis

---


In [7]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.datasets import load_iris


In [8]:
iris=load_iris()
X=iris.data
y=iris.target

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
gnb=GaussianNB()
mnb=MultinomialNB()
bnb=BernoulliNB()

In [12]:
model1=gnb.fit(X_train,y_train)
model2=mnb.fit(X_train,y_train)
model3=bnb.fit(X_train,y_train)

In [13]:
gnb_pred=model1.predict(X_test)
mnb_pred=model2.predict(X_test)
bnb_pred=model3.predict(X_test)

In [17]:
print("Evaluation Metrics for GaussianNB")
print("Accuracy score is:", accuracy_score(y_test,gnb_pred))
print("Confusion matrix is:", confusion_matrix(y_test,gnb_pred))
print("Classification report is:", classification_report(y_test,gnb_pred))

Evaluation Metrics for GaussianNB
Accuracy score is: 1.0
Confusion matrix is: [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification report is:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [19]:
print("Evaluation Metrics for MultinomialNB")
print("Accuracy score is:", accuracy_score(y_test,mnb_pred))
print("Confusion matrix is:", confusion_matrix(y_test,mnb_pred))
print("Classification report is:", classification_report(y_test,mnb_pred))

Evaluation Metrics for MultinomialNB
Accuracy score is: 0.9
Confusion matrix is: [[10  0  0]
 [ 0  9  0]
 [ 0  3  8]]
Classification report is:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.75      1.00      0.86         9
           2       1.00      0.73      0.84        11

    accuracy                           0.90        30
   macro avg       0.92      0.91      0.90        30
weighted avg       0.93      0.90      0.90        30



In [20]:
print("Evaluation Metrics for BernoulliNB")
print("Accuracy score is:", accuracy_score(y_test,bnb_pred))
print("Confusion matrix is:", confusion_matrix(y_test,bnb_pred))
print("Classification report is:", classification_report(y_test,bnb_pred))

Evaluation Metrics for BernoulliNB
Accuracy score is: 0.3
Confusion matrix is: [[ 0 10  0]
 [ 0  9  0]
 [ 0 11  0]]
Classification report is:               precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       0.30      1.00      0.46         9
           2       0.00      0.00      0.00        11

    accuracy                           0.30        30
   macro avg       0.10      0.33      0.15        30
weighted avg       0.09      0.30      0.14        30



/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
