# NumPy Practice Notebook

In [ ]:
import numpy as np


# 1. Creating NumPy Arrays


In [ ]:
# 1D Array
one_d_array = np.array([5, 12, 14, 72, 110])
one_d_array

array([  5,  12,  14,  72, 110])

In [ ]:
type(one_d_array)  # numpy.ndarray


numpy.ndarray

In [ ]:
# 2D Array (Matrix)
two_d_array = np.array([[5, 12, 14], [72, 110, 135]])
two_d_array

array([[  5,  12,  14],
       [ 72, 110, 135]])

# 2. Special Arrays


In [ ]:
zeros_matrix = np.zeros((3, 3))   # All zeros
ones_matrix = np.ones((3, 3))     # All ones
identity_matrix = np.identity(5)  # Identity matrix

zeros_matrix
ones_matrix
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# 3. Range-based Arrays


In [ ]:
range_array = np.arange(10)                 # 0 to 9
step_range_array = np.arange(1, 10, 2)      # Step size = 2
linspace_array = np.linspace(1, 10, 5)      # 5 evenly spaced numbers

range_array
step_range_array
linspace_array

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

# 4. Copy vs View


In [ ]:
copied_array = one_d_array.copy()  # Deep copy
copied_array

array([  5,  12,  14,  72, 110])

# 5. Shape, Dimensions & Size

In [ ]:
one_d_array.shape
two_d_array.shape

(2, 3)

In [ ]:
three_d_array = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

three_d_array
three_d_array.shape     # (layers, rows, columns)
three_d_array.ndim      # Number of dimensions


3

In [ ]:
multi_layer_array = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[1, 2], [3, 4]]
])

multi_layer_array
multi_layer_array.shape
multi_layer_array.size       # Total elements
multi_layer_array.itemsize   # Memory per element
multi_layer_array.dtype      # Data type

multi_layer_array.astype(float)  # Type conversion

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]],

       [[1., 2.],
        [3., 4.]]])

# 6. Python List vs NumPy Array


In [ ]:
import sys

python_list = list(range(100))
numpy_array = np.arange(100)

sys.getsizeof(87) * len(python_list)   # Memory used by list
numpy_array.itemsize * numpy_array.size  # Memory used by NumPy array


800

# 7. Performance Comparison


In [ ]:
import time

# Python List addition
x_list = range(100000)
y_list = range(100000, 200000)

start_time = time.time()
result_list = [x + y for x, y in zip(x_list, y_list)]
time.time() - start_time

0.011062145233154297

In [ ]:
# NumPy Array addition
x_array = np.arange(100000)
y_array = np.arange(100000, 200000)

start_time = time.time()
result_array = x_array + y_array
time.time() - start_time


0.0007998943328857422

# 8. Reshaping & Slicing


In [ ]:
reshaped_array = np.arange(24).reshape(6, 4)
reshaped_array

reshaped_array[2:4, 1:3]   # Row & column slicing
reshaped_array[:, 3]       # Entire column
reshaped_array[:, 2:]      # Column slicing


array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [ ]:

# Iteration
for row in reshaped_array:
    print(row)

for element in np.nditer(reshaped_array):
    print(element)


[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


# 9. Vectorized Operations


In [ ]:
array_a = np.array([1, 2, 3, 4, 5, 6])
array_b = np.array([4, 5, 6, 7, 8, 9])

array_a - array_b
array_a + array_b
array_a * array_b
array_a / array_b
array_a * 2

array_b > 5  # Boolean masking

array([False, False,  True,  True,  True,  True])

# 10. Matrix Operations


In [ ]:
matrix_1 = np.arange(6).reshape(2, 3)
matrix_2 = np.arange(6, 12).reshape(3, 2)

matrix_1.dot(matrix_2)  # Matrix multiplication

matrix_2.max()
matrix_2.min()
matrix_2.min(axis=0)
matrix_2.min(axis=1)
matrix_2.sum(axis=0)
matrix_2.mean()
matrix_2.std()

np.sin(matrix_2)
np.median(matrix_2)


np.float64(8.5)

# 11. Reshaping Utilities


In [ ]:
matrix_2.ravel()        # Flatten
matrix_2.transpose()   # Transpose

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [ ]:
matrix_3 = np.arange(12, 18).reshape(2, 3)


In [ ]:
np.hstack((matrix_1, matrix_3))
np.vstack((matrix_1, matrix_3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
np.vsplit(matrix_1, 2)
np.hsplit(matrix_1, 3)

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

# 12. Fancy Indexing


In [ ]:
fancy_array = np.arange(24).reshape(6, 4)
fancy_array[[2, 3, 4]]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

# 13. Boolean Indexing


In [ ]:
random_matrix = np.random.randint(1, 100, size=20).reshape(4, 5)

random_matrix[random_matrix > 55]
random_matrix[(random_matrix > 55) & (random_matrix % 2 != 0)]

random_matrix[(random_matrix > 55) & (random_matrix % 2 != 0)] = 0
random_matrix

array([[27,  0,  8, 54, 48],
       [ 0, 35, 33, 20, 68],
       [25, 84,  0, 39, 48],
       [ 6, 80, 64, 88, 33]])

# 14. Broadcasting Examples


In [ ]:
# Same shape
a1 = np.arange(8).reshape(2, 4)
a2 = np.arange(8, 16).reshape(2, 4)
a1 + a2


array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
# Row-wise broadcasting
a3 = np.arange(9).reshape(3, 3)
a4 = np.arange(3).reshape(1, 3)
a3 + a4


array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [ ]:
# Column-wise broadcasting
a5 = np.arange(4).reshape(4, 1)
a6 = np.arange(12).reshape(4, 3)
a5 + a6


array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [ ]:
# Scalar broadcasting
a7 = np.arange(1).reshape(1, 1)
a8 = np.arange(20).reshape(4, 5)
a7 + a8

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# 15. Random Functions


In [ ]:
np.random.random()

np.random.seed(1)
np.random.random()

0.417022004702574

In [ ]:
np.random.uniform(1, 100)
np.random.uniform(1, 100, 10)
np.random.uniform(1, 100, 10).reshape(2, 5)

array([[21.24077272, 87.9336262 ,  3.71137173, 67.37628351, 42.31317543],
       [56.31029302, 14.89830692, 20.61204742, 80.2737123 , 96.857896  ]])

In [ ]:
np.random.randint(1, 10)
np.random.randint(1, 100, 10)
np.random.randint(1, 15, 15).reshape(3, 5)

array([[ 8,  4,  7,  6,  2],
       [10,  4,  5,  9,  2],
       [12, 13, 11,  5,  1]])

In [ ]:
random_array = np.random.randint(1, 10, 15)


In [ ]:
np.max(random_array)


np.int64(9)

In [ ]:
np.min(random_array)


np.int64(1)

In [ ]:
np.argmax(random_array)


np.int64(7)

In [ ]:
np.argmin(random_array)

np.int64(2)

In [ ]:
random_array[np.argmax(random_array)]


np.int64(9)

In [ ]:
random_array[np.argmin(random_array)]

np.int64(1)

In [ ]:
random_array = np.random.randint(1, 10, 15)
random_array[random_array%2==1]=-1
random_array


array([-1, -1, -1, -1,  8,  8,  8,  4, -1, -1,  8,  8,  2,  2,  4])

In [ ]:
# where(condition, True, False)
random_array = np.random.randint(1, 50, 6)
np.where(random_array%2==1, -1, random_array)

array([-1, 14, -1, 22, -1, -1])

In [ ]:
random_array = np.random.randint(1, 50, 6)
np.sort(random_array)
np.percentile(random_array,25)


np.float64(12.25)

In [ ]:
np.percentile(random_array,50)

np.float64(13.5)

In [ ]:
np.percentile(random_array,75)


np.float64(20.0)

The End :)